version: '3.8'

services:

  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./traefik:/etc/traefik  # Map a local Traefik configuration directory
    command:
      - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--log.filePath=/etc/traefik/traefik.log"

  geloka-dashboard:
    build:
      context: .
      dockerfile: deployments/prod/Dockerfile
    container_name: geloka-dashboard
    environment:
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geloka-dashboard.rule=Host(`app.localhost`)"
      - "traefik.http.routers.geloka-dashboard.entrypoints=web"

networks:
  default:
    name: app-net
    external: true