FROM node:14-alpine AS build

WORKDIR /app
COPY package*.json ./
COPY yarn*.lock ./
RUN rm -rf node_modules
RUN yarn config set registry https://registry.npmjs.org
RUN yarn install
COPY . ./
RUN yarn build

FROM nginx
COPY deployments/prod/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]